### ISSUE TITLE
fix: fix problems after data check 2022-06-01

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-node#91]
- Fix: problems with ascendex
- Fix: check why there are no valid values for symbols: HPB, TVK, UMB, OLT, CET, AGS, JRT, SMTY, SHOPX, HOPR, PHX, UNN, DFD, ALH
- Fix: why there is too big deviations
	too big deviation for symbol: XLM and source: crex24
	too big deviation for symbol: ZEC and source: crex24
	too big deviation for symbol: RSR and source: sushiswap
	too big deviation for symbol: RSR and source: uniswap
	too big deviation for symbol: UMA and source: probit
	too big deviation for symbol: USDT and source: sushiswap
	too big deviation for symbol: BZRX and source: sushiswap
	too big deviation for symbol: SKM and source: bittrex
	too big deviation for symbol: UST and source: coingecko
	too big deviation for symbol: UST and source: uniswap
	too big deviation for symbol: ESD and source: sushiswap
	too big deviation for symbol: ESD and source: uniswap
- Fix: why not included in response
	["Id bittorrent-2 is not included in response for: coingecko"]
	["Id zkswap is not included in response for: coingecko"]
	["Id agoras is not included in response for: coingecko"]
	["Id SNOB is not included in response for: pangolin-aablock"]
	["Id DYP is not included in response for: pangolin-wavax"]
	["Id FRAX is not included in response for: pangolin-wavax"]
	["Id JOE is not included in response for: pangolin-wavax"]
	["Id SHERPA is not included in response for: pangolin-ave"]
	["Id PNG is not included in response for: pangolin-snob"]
	["Id SPORE is not included in response for: pangolin-snob"]
	["Id PNG is not included in response for: pangolin-spore"]
	["Id SNOB is not included in response for: pangolin-spore"]
	["Id PNG is not included in response for: pangolin-pefi"]
	["Id SNOB is not included in response for: pangolin-pefi"]
	["Id PNG is not included in response for: pangolin-usdt"]
	["Id SNOB is not included in response for: pangolin-png"]
	["Id SPORE is not included in response for: pangolin-png"]
	["Id DYP is not included in response for: pangolin-png"]
	["Id QI is not included in response for: pangolin-png"]
	["Id XAVA is not included in response for: pangolin-png"]
	["Id SHERPA is not included in response for: pangolin-png"]
	["Id AVME is not included in response for: pangolin-png"]
	["Id BCVT/USDT is not included in response for: bitcoincom"]
	["Id BCVT/USDT is not included in response for: hitbtc"]
	["Id AKRO/USDT is not included in response for: binanceusdm"]
	["Id DODO/USDT is not included in response for: binanceusdm"]
	["Id KICK/USDT is not included in response for: stex"]
	["Id BANANA/USDT is not included in response for: stex"]
	["Id STAKE/USDT is not included in response for: huobipro"]
	["Id PNG is not included in response for: pangolin-pefi"]
	["Id SNOB is not included in response for: pangolin-pefi"]
	["Id PNG is not included in response for: pangolin-snob"]
	["Id SPORE is not included in response for: pangolin-snob"]
	["Id SNOB is not included in response for: pangolin-aablock"]
	["Id SNOB is not included in response for: pangolin-png"]
	["Id SPORE is not included in response for: pangolin-png"]
	["Id DYP is not included in response for: pangolin-png"]
	["Id QI is not included in response for: pangolin-png"]
	["Id XAVA is not included in response for: pangolin-png"]
	["Id SHERPA is not included in response for: pangolin-png"]
	["Id AVME is not included in response for: pangolin-png"]
	["Id SHERPA is not included in response for: pangolin-ave"]

**Comment by cehali** [comment]
- Fix: problems with ascendex -> Removed USDC/USDT pair, rest of them started to work
